### PR TITLE
Fix issue where properties weren't getting removed if a type was specified.

### LINKED ISSUE #293: RFC: Don't pass undefined and null values to property.type
The function passed to the `type` property of a property object is typically used to coerce values to the desired type before giving it to the property's setter. In doing this, though, the recently added ability to pass `undefined` or `null` to a component's property to remove the corresponding attribute is lost, and JS types don't always return `undefined` when passed `undefined` (e.g. `Number(undefined) -> NaN`, `String(undefined) -> "undefined"`).

It is possible to get around this by wrapping each JS type in your own function:

```js
function type(fn) {
  return (value) => {
    if(value === undefined || value === null) return value;
    return fn(value);
  };
}

...

myProperty: {
  type: type(Number),
},
```

...However it is a bit of a hassle :)

Is there a use case for the user handling `undefined` or `null` specially (where you could otherwise use `false`)?

### PR DESCRIPTION
**Pull request by treshugart**
If you specify a type and pass `null` or `undefined`, properties weren't being unset.

Fixes #293.

### CODE REVIEW

File: src/lifecycle/properties.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ function property (elem, name, prop) {
 
       if (isBoolean && internalValue) {
         this.setAttribute(prop.attr, '');
-      } else if (internalValue == null || isBoolean && !internalValue) {
+      } else if (value == null || isBoolean && !internalValue) {
```
Comment (treshugart) [inline src/lifecycle/properties.js]: I'm not sure if we should be doing this as far down as we are here. What this means is that the value is still being coerced and passed to the setter. This could cause the attribute to be removed even if the coercing function made it a valid value.

Comment (marcoms) [inline src/lifecycle/properties.js]: In my opinion if the value is `undefined` then I think that we should skip calling `prop.type()` on it altogether. I can't imagine anyone would want to handle `undefined` as a valid value for a component's property (perhaps `null` would be appropriate as it often intentionally denotes "not applicable", "empty", etc. for example in `Element#querySelector(".no-elements-with-this-class") === null`, `Element#getAttribute("no-such-attribute") === null`).

Comment (treshugart) [inline src/lifecycle/properties.js]: Good call.

Comment (treshugart) [inline src/lifecycle/properties.js]: @marcoms updated in 3b6dcaf.

**Comment by treshugart** [comment]
> I'd say that the type coercion be skipped, but the setter still be called later on

That's probably a good idea. After finalising https://github.com/skatejs/skatejs/pull/307 I'd like to focus on the property lifecycle. See https://github.com/skatejs/skatejs/issues/281 for details.

**Comment by marcoms** [comment]
>I'd say that the type coercion be skipped, but the setter still be called later on

@treshugart is there any scope for discussion at this time or do you want to wait until #281 is settled?

**Comment by treshugart** [comment]
@marcoms sure, could be implemented alongside #281.
