### PR TITLE
fix: make skate work with multiple versions on one page

### LINKED ISSUE #416: Ensure master works with other versions on the same page.
Would be nice to write a test for this since it's API.

### PR DESCRIPTION
**Pull request by joscha**
This adds a test with multiple skate versions on one page and fixes the global registry due to a forgotten version constant.

PTAL @treshugart 

closes #416.

### CODE REVIEW

File: test/unit/multiple-versions.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import helperElement from '../lib/element';
+import helperFixture from '../lib/fixture';
+import helperReady from '../lib/ready';
+
+import skateMaster from '../../src/index';
+// FIXME Babel seems to wreck this one - skate is exposed, not skate014
+import {skate as skate014} from '../skate/0.14.3.js'; // eslint-disable-line no-unused-vars
```
Comment (joscha) [inline test/unit/multiple-versions.js]: You'd expect the exported `skate` symbol to be imported into the local `skate014` symbol, but somehow Babel messes that up and populates a local `skate` symbol. This can't be redefined, so I need to write it into an `oldSkate` symbol. We can fix this with a newer Babel version later, maybe.

File: src/shared/vars.js [hunk 2]
```diff
@@ -1,4 +1,6 @@
-const VERSION = '__skate_0_14_0';
```
Comment (joscha) [inline src/shared/vars.js]: o_O

File: test/skate/0.14.3.js [hunk 3]
```diff
@@ -0,0 +1 @@
...B=e(I),K=__9cff21a9f41cc9ecfe56139e1040c954,q=e(K),F=__c6f5e18624750ce93a74df6369c85ef0,J=e(F),R=__43714db526496b3dd90353996f6dce09,Z=e(R),G=__164e5750c20526cb74a9e443b730eeff,Q=e(G),U=__6e1dfed2b03894ef63a4b65d5038d223,W=e(U),X=window.HTMLElement,Y=(0,L["default"])(function(){(0,Q["default"])(document.documentElement.childNodes,function(e){for(var t=q["default"].find(e),r=t.length,n=0;r>n;n++)t[n].prototype.createdCallback.call(e);for(var n=0;r>n;n++)t[n].prototype.attachedCallback.call(e)})});return o.create=f["default"],o.emit=l["default"],o.fragment=s["default"],o.init=b["default"],o.properties=v["default"],o.ready=y["default"],o.render=x["default"],o.version=m["default"],d["default"]=o,a.exports=d["default"],a.exports}.call(this),("undefined"==typeof window?global:window).__9a43120147a4f5a325d55b702c284d36=function(){function e(e){return e&&e.__esModule?e:{"default":e}}function t(){return window.skate=d,this}var r={exports:{}},n=r.exports;Object.defineProperty(n,"__esModule",{value:!0});var o=__abb93179bdc0236a6e77d3eae07c991c,a=e(o),d=window.skate;return a["default"].noConflict=t,window.skate=a["default"],n["default"]=a["default"],r.exports=n["default"],r.exports}.call(this);
```
Comment (joscha) [inline test/skate/0.14.3.js]: There is no easy way in npm to have multiple dependencies on the same version of a package, so I chose to check `0.14.3` in.

Comment (treshugart) [inline test/skate/0.14.3.js]: +1, that's totally fine. For posterity this [was discussed](https://github.com/npm/npm/issues/5499) in NPM itself and they were pretty clear they weren't going to change NPM to allow this.

File: src/shared/vars.js (hunk 2 above)
Comment (treshugart) [inline src/shared/vars.js]: ?

Comment (joscha) [inline src/shared/vars.js]: Just added that to emphasise that this has been broken since 0.14.0 - no action needed :)

Comment (joscha) [inline src/shared/vars.js]: Well actually...potentially we could port this fix back to the 0.14 branch.

Comment (jpnelson) [inline src/shared/vars.js]: It's probably used much less now since `skate` is no longer on the window, you'd have to figure out the version inside a closure.

Comment (joscha) [inline src/shared/vars.js]: @jpnelson sorry, I don't understand?

**Comment by jpnelson** [comment]
LGTM

**Comment by treshugart** [comment]
lgtm

File: src/shared/vars.js (hunk 2 above)
Comment (jpnelson) [inline src/shared/vars.js]: don't worry, I thought this was just used for `window.skate.version`, but I see it has other uses now
