### PR TITLE
Fixes #813 V1 component constructor

### LINKED ISSUE #813: Tests fails on Chrome 55 (Canary)
Hi! I wanted to run the testsuite in a WebComponents V1 environment, so I decided to run them in Chrome 55, currently in canary and turns out that they fail. Apparently the issue appears when running the [Component constructor](https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L76-L80), which is only used when V1 is available.

```javascript
const elem = HTMLElement.call(this, self);
```
```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator,
this DOM object constructor cannot be called as a function
```

Apparently is not allowed to create an element in such way. So my question is, how are we actually testing that the library works with V1? maybe Im just using a buggy version of Chrome and this is fine :)

If that's not the case, maybe we can use something like `document.createElement` or create a dummy function which has the `HTMLElement` prototype? 

Let me know if this makes sense to you, thanks!!

### PR DESCRIPTION
**Pull request by bengummer**
copied commits from https://github.com/skatejs/skatejs/pull/817/commits and then made some changes to get tests passing on IE 11/10/9 and Safari 9

### CODE REVIEW

File: src/api/component.js [hunk 1]
```diff
@@ -74,10 +74,11 @@ function callDisconnected(elem) {
 }
 
 // v1
-function Component(self) {
-  const elem = HTMLElement.call(this, self);
-  callConstructor(elem);
-  return elem;
+function Component(...args) {
+  const hasReflect = window.hasOwnProperty('Reflect'); // eslint-disable-line no-prototype-builtins
+  const elm = (hasReflect && Reflect.construct(HTMLElement, args, this.constructor)) || HTMLElement.call(this, args[0]);
```
Comment (bengummer) [inline src/api/component.js]: doing `Reflect && Reflect.construct(...)` here didn't work on IE

**Comment by bengummer** [comment]
PR based on the awesome work by @zzarcon in https://github.com/skatejs/skatejs/pull/817/files#diff-d3ff8469a13e890ec2a5c73b90df75abR29

Needed to create this branch in the skatejs/skatejs repo so that Saucelabs browser tests would run

File: src/api/component.js [hunk 2]
```diff
@@ -74,10 +74,11 @@ function callDisconnected(elem) {
 }
 
 // v1
-function Component(self) {
-  const elem = HTMLElement.call(this, self);
-  callConstructor(elem);
-  return elem;
+function Component(...args) {
+  const hasReflect = window.hasOwnProperty('Reflect'); // eslint-disable-line no-prototype-builtins
```
Comment (treshugart) [inline src/api/component.js]: This should probably live at the top level as we probably don't need a lazy check for it. You can also do `'Reflect' in window`.

File: src/api/component.js [hunk 3]
```diff
@@ -189,6 +191,7 @@ Component.prototype = Object.create(HTMLElement.prototype, {
   createdCallback: {
     configurable: true,
     value() {
+      setElementAsDefined(this);
```
Comment (treshugart) [inline src/api/component.js]: I knew this was moved to `connectedCallback()`, but why do we need this here? Shouldn't it be causing tests in Canary to fail?

Comment (bengummer) [inline src/api/component.js]: you're right, just didn't get picked up in CI - fixing now

File: src/api/component.js [hunk 4]
```diff
@@ -11,6 +11,9 @@ import debounce from '../util/debounce';
 import getAllKeys from '../util/get-all-keys';
 import getOwnPropertyDescriptors from '../util/get-own-property-descriptors';
 
+const setElementAsDefined = elem => elem.setAttribute('defined', '');
+const hasReflect = 'Reflect' in window;
```
Comment (zzarcon) [inline src/api/component.js]: Should we move this to [support](https://github.com/skatejs/skatejs/blob/master/src/util/support.js) then?

File: src/api/component.js (hunk 3 above)
Comment (zzarcon) [inline src/api/component.js]: I thought this needs to be called here for V0 support, otherwise it will never be called since it has been extracted from `callConstructor`? Maybe Im wrong, but tests works for me on Chrome.

**Comment by zzarcon** [comment]
@bengummer thanks a lot for taking over my initial work 🎉 🚀 !

I think I had something wrong configured locally and the tests were not working fine on CI, also didn't know that this was breaking Safari and IE, I thought there the constructor was not called since V1 and maybe V0 was not available at all hehe.

Anyways this looks good to me, I pretty much just did what @treshugart told me, so the job is mostly from him!

File: src/api/component.js (hunk 4 above)
Comment (bengummer) [inline src/api/component.js]: good idea

**Comment by treshugart** [comment]
@zzarcon don't be silly. You jumped in the deep end and swam, even if I was standing lifeguard :). Nice work both of you!

**Comment by treshugart** [comment]
I think the only last thing on here is to ensure we're releasing a breaking change with this (unless there's evidence to suggest against it). The reason I say this is that moving attribute linking to when the element is connected might break expectations for some, even if we're still ensuring props are initialised.

**Comment by bengummer** [comment]
fyi @treshugart and @zzarcon: i've tried to defer the v1 attribute syncing until the `connectedCallback` happens and got most of the way, but for some reason the `connectedCallback` wasn't being triggered when I ran the tests in Chrome 55 so i couldn't get the tests to pass.

i've just added a commit with my work in progress trying to defer the attr sync. I'm away for the next 5 or so days so feel free to pick up from here otherwise i will continue when i'm back.

thanks for your help @zzarcon ! and for the guidance @treshugart :)

**Comment by zzarcon** [comment]
@treshugart I don't have that much experience with the lib but I also think this is a breaking change and will be better to do bump the version, even if maybe no users will be affected right now 😿

File: src/api/component.js [hunk 5]
```diff
@@ -74,10 +75,10 @@ function callDisconnected(elem) {
 }
 
 // v1
-function Component(self) {
-  const elem = HTMLElement.call(this, self);
-  callConstructor(elem);
-  return elem;
+function Component(...args) {
+  const elm = (hasReflect && Reflect.construct(HTMLElement, args, this.constructor)) || HTMLElement.call(this, args[0]);
```
Comment (bradleyayers) [inline src/api/component.js]: Why not use a proper ternary here?

Comment (bradleyayers) [inline src/api/component.js]: is `elm` a new convention? I thought `elem` was the standard in skatejs.

File: src/api/component.js [hunk 6]
```diff
@@ -138,6 +139,10 @@ Component.prototype = Object.create(HTMLElement.prototype, {
   connectedCallback: {
     configurable: true,
     value() {
+      // will eventually need to callsomething like this here:
+      // Ctor[$props](elem);
+      console.log('connectedCallback')
```
Comment (bradleyayers) [inline src/api/component.js]: Stray console.log?

File: test/unit/api/component.js [hunk 7]
```diff
@@ -52,7 +52,7 @@ describe('api/Component', () => {
   });
 
   describe('updated function', () => {
-    it('should return true if a prop changes', () => {
+    it.only('should return true if a prop changes', () => {
```
Comment (bradleyayers) [inline test/unit/api/component.js]: Stray `.only`.

File: test/unit/lifecycle/defined.js [hunk 8]
```diff
@@ -5,9 +5,16 @@ describe('lifecycle/defined', () => {
...
+  it('should add the [defined] attribute when the element is upgraded', (done) => {
     const Elem = define('x-test', {});
     const elem = new Elem();
-    expect(elem.hasAttribute('defined')).to.equal(true);
+
+    document.body.appendChild(elem);
+
+    setTimeout(() => {
+      expect(elem.hasAttribute('defined')).to.equal(true);
+      document.body.removeChild(elem);
```
Comment (mcorbanini) [inline test/unit/lifecycle/defined.js]: This should be covered in `afterEach` right?

File: test/unit/lifecycle/defined.js [hunk 9]
```diff
@@ -5,9 +5,16 @@ describe('lifecycle/defined', () => {
...
 
-  it('should add the [defined] attribute when the element is upgraded', () => {
+  it('should add the [defined] attribute when the element is upgraded', (done) => {
     const Elem = define('x-test', {});
     const elem = new Elem();
-    expect(elem.hasAttribute('defined')).to.equal(true);
+
+    document.body.appendChild(elem);
+
+    setTimeout(() => {
```
Comment (mcorbanini) [inline test/unit/lifecycle/defined.js]: Why not using `afterMutations` ?

Comment (zzarcon) [inline test/unit/lifecycle/defined.js]: Oh good point, didn't know about that utility

File: src/api/component.js (hunk 3 above)
Comment (treshugart) [inline src/api/component.js]: If it works in Chrome it should be fine. We'll do another breaking change soon to remove v0 support, so as long as the tests pass for it I'm okay with whatever works for now as long as we can get v1 fixed up.

File: src/api/component.js (hunk 5 above)
Comment (treshugart) [inline src/api/component.js]: +1 for `elem`

**Comment by treshugart** [comment]
Ok, I just made a bunch of updates. Things that still need to happen:

1. On `connected`, sync attributes (can probably just re-set props to their same values).
2. Write test for 1 (probably should do this first, but I listed 1 first for context).
3. Update prop tests so that they test the attribute values after connected and after mutations.

File: test/unit/lifecycle/defined.js (hunk 8 above)
Comment (treshugart) [inline test/unit/lifecycle/defined.js]: I don't think there's an after each in those tests.

File: test/unit/lifecycle/defined.js (hunk 9 above)
Comment (treshugart) [inline test/unit/lifecycle/defined.js]: done

File: test/unit/api/component.js (hunk 7 above)
Comment (treshugart) [inline test/unit/api/component.js]: done

File: src/api/component.js (hunk 6 above)
Comment (treshugart) [inline src/api/component.js]: removed

File: src/api/component.js (hunk 5 above)
Comment (treshugart) [inline src/api/component.js]: changed to `elem`

Comment (treshugart) [inline src/api/component.js]: updated to use a ternary

File: src/api/component.js (hunk 4 above)
Comment (treshugart) [inline src/api/component.js]: done

**Comment by bengummer** [comment]
This is now ready for PR again, we've got the attributes being synced from props on elem connect. Also have tests for this (see new `delayed-attributes.js` tests). There was actually quite a bit of refactoring needed for the existing tests, a lot of `afterMutations` as well as some issues on IE10/IE11/FF.

**Comment by treshugart** [comment]
Totes approving this! I think this introduces some ambiguity about whether an attribute or property *should* take precedence due to the delay of syncing but I don't know there's much we can do about that until we come up with an answer for #838.
