### PR TITLE
Fix updating the property when setting a linked attribute

### LINKED ISSUE #316: Setting a linked attribute doesn't change the value of the property
Setting the attribute directly doesn't change the property.

```
    skate('my-el', {
      properties: {
        test: {
          attr: 'test2'
        }
      }
    });

    ...

    el.test = 'value1';
    el.setAttribute('test2', 'value2');
    console.log(el.test); // will print 'value1' instead of 'value2'
```

### PR DESCRIPTION
**Pull request by bqx**
PR to fix #316

### CODE REVIEW

File: test/unit/lifecycle/properties.js [hunk 1]
```diff
@@ -76,6 +76,41 @@ describe('lifecycle/properties', function () {
...
+        }
+      });
+
+      var el = fixture(`<${elem.safe}></${elem.safe}>`).querySelector(elem.safe);
+      skate.init(el);
+
+      el.test = 'value1';
+      el.setAttribute('test', 'value2');
+      expect(el.test).to.equal('value2');
+    });
```
Comment (bqx) [inline test/unit/lifecycle/properties.js]: This test passed without any of the changes made, but is added here for better coverage.

Comment (treshugart) [inline test/unit/lifecycle/properties.js]: +1. Thanks!
