### PR TITLE
fix: Fix issues integrating with the polymer / webcomponents polyfills.

### LINKED ISSUE #901: Integrate skatejs-web-components with Polymer / Webcomponent polyfills
This removes the usage of the skatejs-named-slots polyfill and pulls in the polyfills as stated in 
https://github.com/skatejs/web-components/issues/26 and implemented in https://github.com/skatejs/web-components/pull/27.

This is essentially only for the purposes of testing, but initial tests uncovered a minor issue with the ShadyDOM polyfill, so there are a couple code changes that have to be made. More explained in the PR.

This should be treated as a patch release to fix issues integrating with those polyfills as well as simplifying event handling code.

### PR DESCRIPTION
**Pull request by treshugart**
Simplified event handling code and updated tests to be more clear.

fixes #901

### CODE REVIEW

File: src/api/vdom.js [hunk 1]
```diff
@@ -44,17 +44,22 @@ function applyEvent (elem, ename, newFunc) {
...
   }
 
-  const oldFunc = events[ename];
-
-  // Remove old listener so they don't double up.
-  if (oldFunc) {
-    elem.removeEventListener(ename, oldFunc);
+  // Undefined indicates that there is no listener yet.
+  if (events[ename] === undefined) {
+    // We only add a single listener once. Originally this was a workaround for
```
Comment (treshugart) [inline src/api/vdom.js]: The original issue is this one https://github.com/webcomponents/shadydom/issues/24. In that test we were adding the same callback more than once, thus they didn't get removed.

File: karma.browsers.js [hunk 2]
```diff
@@ -0,0 +1 @@
+module.exports = require('skatejs-build/karma.browsers');
```
Comment (treshugart) [inline karma.browsers.js]: Added because of build lib update.

File: package.json [hunk 3]
```diff
@@ -24,15 +24,14 @@
   ],
   "dependencies": {
     "incremental-dom": "0.4.1",
-    "window-or-global": "^1.0.1"
+    "window-or-global": "1.0.1"
```
Comment (treshugart) [inline package.json]: Pinned this to ensure consistency in dependencies.

File: package.json [hunk 4]
```diff
@@ -24,15 +24,14 @@
...
   },
   "devDependencies": {
-    "birdpoo": "0.x",
-    "document-register-element": "1.x",
-    "react": "15.x",
-    "react-dom": "15.x",
-    "skatejs-build": "9.x",
-    "skatejs-web-components": "2.0.2"
+    "birdpoo": "0",
```
Comment (treshugart) [inline package.json]: Boyscout: I realised you could just do this. Removes redundancy in the `.x` suffix.

File: src/api/vdom.js [hunk 5]
```diff
@@ -44,17 +44,22 @@ function applyEvent (elem, ename, newFunc) {
     events = elem[$currentEventHandlers] = {};
   }
 
-  const oldFunc = events[ename];
-
-  // Remove old listener so they don't double up.
-  if (oldFunc) {
-    elem.removeEventListener(ename, oldFunc);
+  // Undefined indicates that there is no listener yet.
```
Comment (treshugart) [inline src/api/vdom.js]: The core change is this.

File: test/unit/vdom/events.js [hunk 6]
```diff
@@ -29,31 +26,11 @@ describe('vdom/events (on*)', () => {
...
-        expect(shadowDiv.textContent).to.equal('1');
-        emit(shadowDiv, 'event');
-        expect(el._test).to.equal(2);
-
-        props(el, { test: el.test + 1 });
-        expect(shadowDiv.textContent).to.equal('2');
-        emit(shadowDiv, 'event');
-        expect(el._test).to.equal(3);
-      },
+      () => expect(el.shadowRoot.textContent).to.equal('0'),
```
Comment (treshugart) [inline test/unit/vdom/events.js]: This essentially tests the same thing in a simpler manner. However the previous test didn't take into account things that may happen after mutations very well, this ensures that anything that might happen in a microtask, should happen, and that things are more direclty tested.

File: test/unit/vdom/events.js [hunk 7]
```diff
@@ -108,16 +85,33 @@ describe('vdom/events (on*)', () => {
...
       }
     }))();
     fixture(myel);
+    let div
     afterMutations(
-      () => {}, // .render()
-      () => {
-        emit(myel.shadowRoot.firstChild, 'test');
-      },
+      () => (div = myel.shadowRoot.firstChild),
```
Comment (treshugart) [inline test/unit/vdom/events.js]: I added several more assertions here since we rely on `null` and `undefined` explicitly in the event binding logic and we need to make sure that if an event is set to one of those that it doesn't screw it up. Also passed falsy / truthy values to ensure that we only allow functions.

File: package.json (hunk 4 above)
Comment (nadiam84) [inline package.json]: I remember this discussion, that `1.x` is confusing for some people, everyone is used to `^1.0.0`. Don't you think this would be even more confusing?

**Comment by lukebatchelor** [comment]
LGTM 👍

File: src/api/vdom.js [hunk 8]
```diff
@@ -44,17 +44,22 @@ function applyEvent (elem, ename, newFunc) {
...
+  if (typeof events[ename] === 'undefined') {
```
Comment (nadiam84) [inline src/api/vdom.js]: Sure this shouldn't be `!==`?

Comment (nadiam84) [inline src/api/vdom.js]: never mind...

File: package.json (hunk 4 above)
Comment (treshugart) [inline package.json]: I find specifying the whole thing confusing, TBH. I much prefer this, but maybe that's just me?

File: src/api/vdom.js (hunk 8 above)
Comment (treshugart) [inline src/api/vdom.js]: No, if it's `undefined`, that means there's no listener yet, so we must bind one in order to trigger anything that gets bound via a property. Later we set the handler in the `events` map.

This is a workaround for https://github.com/webcomponents/shadydom/issues/24 but I like the logic much better anyways. There'd be pretty much zero overhead for adding a single noop listener, and optimising for the common use case, generally (from experience) once you add a listener, you're going to keep it there.

File: package.json (hunk 4 above)
Comment (nadiam84) [inline package.json]: I prefer `x` :D But there were this discussion and complains about skate's complexity ;) But it's your choice.

File: src/api/vdom.js (hunk 8 above)
Comment (nadiam84) [inline src/api/vdom.js]: feels like it's breaking change...

Comment (treshugart) [inline src/api/vdom.js]: It's definitely not a breaking change. The API stays the same; nothing changes for the user.
