### PR TITLE
Unique tag names in tests to avoid re-registration errors (#120)

### LINKED ISSUE #120: Some tests fail in Chrome with "a type with that name is already registered"
This is due to the fact that the tests run in a single browser session and thus attempt to re-register element tag names, causing the error:

```text
Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'my-element'. A type with that name is already registered.
```

### PR DESCRIPTION
**Pull request by nicolasv**
Fixes #120.

### CODE REVIEW

File: test/unit/registration.js [hunk 1]
```diff
@@ -112,9 +114,11 @@ describe('Returning a constructor', function () {
   describe('when an extends option is specified', function () {
     var Div;
     var div;
+    var tagName;
 
     beforeEach(function () {
-      Div = skate('my-element', {
+      tagName = helpers.uniqueTagName('my-element');
```
Comment (nicolasv) [inline test/unit/registration.js]: It would be nice to use destructuring assignment here, i.e.,

```js
{'my-element': tagName} = helpers.uniqueTagName('my-element');
```
but it seems for destructuring assigment doesn't work for existing `var`s (unless I'm mistaken).

File: test/lib/helpers.js [hunk 2]
```diff
@@ -1,8 +1,29 @@
...
+   *
+   * @param id the identifier for the tag
+   * @returns {Object.<string, string>} an object with the key 'id' mapped to
+   *   the value of the id and the value of the id mapped to a unique tag name
+   */
+  uniqueTagName: function (id) {
+    var safeId = id + '-' + (tagNameCounter++).toString();
+    var tagName = {id: id};
+    tagName[id] = safeId;
+    return tagName;
```
Comment (nicolasv) [inline test/lib/helpers.js]: Maybe returning an object like

```js
return {unsafe: id, safe: safeId};
```
provides a better API. Usages would end up looking like:

```js
var tagName = helpers.uniqueTagName('my-element');
skate(tagName.safe, /* ... */)
var {safe: tagName, unsafe: unsafeTagName} = helpers.uniqueTagName('my-element');
```

File: test/lib/helpers.js [hunk 3]
```diff
@@ -10,9 +31,18 @@ export default {
     return element;
   },
 
-  fixture: function (html) {
-    var fixture = document.getElementById('fixture');
+  fixture: function (html, tagName) {
+    if (typeof html === 'string' && typeof tagName !== 'undefined') {
```
Comment (nicolasv) [inline test/lib/helpers.js]: This entire block should be moved into the `if (typeof html === 'string')` block below.

Comment (nicolasv) [inline test/lib/helpers.js]: Done in de06358.

File: test/lib/helpers.js (hunk 2 above)
Comment (nicolasv) [inline test/lib/helpers.js]: Done in 0f93a09.
