### PR TITLE
Fixed multiple definition of properties on the same constructor.

### LINKED ISSUE #1111: lost props when creating multiple instance of a component simultaneously
When creating multiple instance of a given component in 1 shot through this kind of code: 
```js
var host = document.querySelector('#container');
host.innerHTML = '<x-hello-world name="first"></x-hello-world>' +
  '<x-hello-world name="second"></x-hello-world>';
```

Only the second one will render with the right name props. The first one will have an undefined name props during render.

### PR DESCRIPTION
**Pull request by freeman**
fixes #1111 

Properties were defined at each instantiation of a given element. These caused the backing symbol to be changed for each instance but as the properties are defined on the prototype, this meant that all instances apart from the last actually lost track of the props value.

This was visible in usage when instantiating the same component multiple times in a page at the same time (with innerHTML for example). Only the last one actually got access to the props when render time comes (after debounce).

### CODE REVIEW

**Comment by Hotell** [comment]
Can you pls create an issue before submitting PR and referencing it within PR ?

thanks!

**Comment by freeman** [comment]
sorry about that, done.

**Comment by freeman** [comment]
I see that this PR no longer merges cleanly. Do you want me to rebase it ?

Is there any issue with it that prevents it from being integrated ?

**Comment by treshugart** [comment]
@freeman shouldn't be. Feel free to rebase then we'll merge.

**Comment by freeman** [comment]
rebased onto `5.x`

**Comment by treshugart** [comment]
Cool! @Hotell can you give the thumbs up on this, please?

The build would be failing because it's not coming from the skatejs org. Eventually we'll need to come up with a solution for contribs. Happy to merge if you think it's okay.

File: src/util/with-props.js [hunk 1]
```diff
@@ -8,7 +8,9 @@ const _syncingPropertyToAttribute = sym('_syncingPropertyToAttribute');
 export const _updateDebounced = sym('_updateDebounced');
 
 export function defineProps (Ctor) {
-  if (!Ctor[_definedProps]) {
+  if (Ctor[_definedProps]) {
+    return;
+  } else {
```
Comment (Hotell) [inline src/util/with-props.js]: just a nitpick.

Else is unnecessary and makes code less readable

consider:
```js
export function defineProps (Ctor) {
  if (Ctor[_definedProps]) {
    return
  }

  Ctor[_definedProps] = true;

  const { prototype } = Ctor;
  const props = normPropDefs(Ctor);

// ...

}

**Comment by freeman** [comment]
@Hotell absolutely clearer this way. Just pushed an amended version, thanks.
