### PR TITLE
fix: Fix for setting a linked attribute not updating the property

### LINKED ISSUE #738: Cannot set property via linked attribute
This happens when a property has a linked attribute, and then the value of the property is immediately set to the same value as its initial value once it is initialised (e.g. during the created callback, or immediately after instantiating an instance of the component):

This seems to be the same issue as #733 , except that it occurs when setting to the initial value again immediately.

Example:

```
define('my-component', {
  created(el) {
    el.myProp = 'initial value';
  },
  props: {
    myProp: {
      attribute: true
    }
  }
});
```

```
<my-component my-prop="initial value"></my-component>
```
```
document.querySelector('my-component').setAttribute('my-prop', 'new value'); // does nothing
```

### PR DESCRIPTION
**Pull request by bqx**
Followup to the fix for #733, check that the actual attribute value has changed after serialization

Fixes #738

---

The issue was that we were only checking that value had changed, not that the attribute value had changed (which was the root cause of the problem). We need to check that the new attribute value (i.e. `serializedValue`) is not new.

Also moved tests to a new section at the bottom of the file, and added one new test.

### CODE REVIEW

File: src/lifecycle/props-init.js [hunk 1]
```diff
@@ -96,13 +95,16 @@ function createNativePropertyDefinition(name, opts) {
     const attributeName = data(this, 'propertyLinks')[name];
     if (attributeName && !propData.settingAttribute) {
       const serializedValue = opts.serialize(newValue);
+      const currentAttrValue = this.getAttribute(attributeName);
+      const attributeChanged = !((empty(serializedValue) && empty(currentAttrValue)) ||
+                                (serializedValue === currentAttrValue));
       propData.syncingAttribute = true;
       if (shouldRemoveAttribute || empty(serializedValue)) {
```
Comment (treshugart) [inline src/lifecycle/props-init.js]: You can probably store the check to `empty(serializedValue)` since it's used more than once.

**Comment by treshugart** [comment]
LGTM pending comments!

**Comment by lukebatchelor** [comment]
Cool! LGTM

**Comment by bqx** [comment]
LGTM

**Comment by treshugart** [comment]
lgtm lgtm lgtm lgtm
