### PR TITLE
fix: Fix issue causing false to not remove attributes from virtual el…

### LINKED ISSUE #819: Attribute not removed from normal dom element when passed false
Given the component:

```js
define('x-test', {
  props: {
    test: prop.boolean(),
  },
  render(e) {
    vdom.element('div', { test: e.test });
  },
})
```

The rendered `<div />` will still have the `test` attribute even when it's passed `false`. It should be removed.

### PR DESCRIPTION
**Pull request by treshugart**
…ements.

fixes #819

### CODE REVIEW

File: test/unit/vdom/properties.js [hunk 1]
```diff
@@ -38,13 +38,21 @@ describe('vdom/properties', () => {
 
   it('false should remove the attribute', done => {
```
Comment (nadiam84) [inline test/unit/vdom/properties.js]: `undefined` and `null` should ... ? ;)

Comment (lukebatchelor) [inline test/unit/vdom/properties.js]: Agreed that we should explicitly have an answer to this, but not sure what the expected behaviour is/should be...

Comment (treshugart) [inline test/unit/vdom/properties.js]: We never handled those before. The reasoning was to try and make as little bespoke behaviour on top of HTML as possible. Meaning `setAttribute('attr', false)` will set `attr="false"` (stringify). It does the same will `null` and `undefined`. Changing that so that `false` would remove the attribute (which is what was originally done here and this is a bug) made it so that we keep the bespoke footprint small. Technically adding `null` / `undefined` would be a breaking change.

We can do this, but I'd rather do it as a separate issue to make the change deliberate if we think that's a good idea. Thoughts?

**Comment by treshugart** [comment]
Merging now as I've raised #832 for possibly adding `null` / `undefined` in a breaking change.
