### PR TITLE
fix(vdom): Fix issue where the attribute applicator was trying to set…

### LINKED ISSUE #566: Problems with iDOM default attribute setter
The check for `name in elem` will set properties for svg elements that have only getters. To rectify this, we should:

1. remove that check and move it into the event setter so that it can set events as props if available
2. remove the need for internalData as we can just check `elem.constructor.properties`

A test should be written for creating an SVG element and setting `height` which has only a getter.

### PR DESCRIPTION
**Pull request by treshugart**
… readonly properties on SVG ele

Fixes #566

### CODE REVIEW

**Comment by lukebatchelor** [comment]
lgtm

File: src/api/vdom.js [hunk 1]
```diff
@@ -94,8 +94,13 @@ attributes[symbols.default] = function (elem, name, value) {
...
 
-  // Set defined props on the element directly.
-  if (name in elem) {
+  // Set defined props on the element directly. This ensures properties like
+  // "value" on <input> elements get set correctly. Setting those as attributes
+  // doesn't always work and setting props is faster than attributes.
+  //
+  // However, certain props on SVG elements are readonly and error when you try
+  // to set them.
+  if (name in elem && !('ownerSVGElement' in elem)) {
```
Comment (nadiam84) [inline src/api/vdom.js]: why not `elem.hasOwnProperty('ownerSVGElement')`?

**Comment by nadiam84** [comment]
lgtm

File: test/unit/vdom/properties.js [hunk 2]
```diff
@@ -31,14 +31,13 @@ describe('vdom/properties', () => {
 
   it('should not set properties on SVG elements', done => {
     expect(() => {
-      new (define('x-test', { // eslint-disable-line no-new
+      const Test = define('x-test', {
         render() {
-          vdom.element('svg', { height: 100 });
+          vdom.element('svg', { width: 100 });
```
Comment (bqx) [inline test/unit/vdom/properties.js]: Any reason for setting `width` instead of `height` here? Are they both read-only?

File: src/api/vdom.js (hunk 1 above)
Comment (bqx) [inline src/api/vdom.js]: Is it possible to make this fix more general by checking that the property isn't read-only, or is there some performance consideration here?

**Comment by bqx** [comment]
lgtm pending comments

File: test/unit/vdom/properties.js (hunk 2 above)
Comment (treshugart) [inline test/unit/vdom/properties.js]: Width was the prop I had issues with but height would reproduce it too. It just got changed when I was messing with the test. It won't matter which one it is, though.

File: src/api/vdom.js (hunk 1 above)
Comment (treshugart) [inline src/api/vdom.js]: @nadiam84 it's not an own property. You'd have to walk the prototype chain depending on how far up `SVGElement` is.

@bqx You'd have to do `Object.getOwnPropertyDescriptor()` and check `writable`, but just like `hasOwnProperty()` you'd have to do it at the prototype level as it wouldn't be an own property on the element instance.

Depending on the element, how far up you'd have to walk can vary and walking prototype chains can be expensive. Even so, this is performance critical code. The less object accessing and function calls the better.
