### PR TITLE
Call renderer when props change

### LINKED ISSUE #1134: Doesn't rerender when props change
I think [this line](https://github.com/skatejs/skatejs/blob/dac2c4dff7824221aebf3bf55c402c04b0ad8674/src/with-props.js#L92) is wrong.  It should be `!keys(prev).every(k => prev[k] === next[k])`.

Going to try my hand at writing a test for this :D

### PR DESCRIPTION
**Pull request by matthewp**
This fixes #1134.

When properties change, the renderer function is called. This is done by implementing propsChangedCallback within with-render.

Also fixes an issue where any renders after the first would not result in the shadowRoot being updated, because we weren't passing the preact component back into preact's `render` method.

### CODE REVIEW

File: src/with-component.js [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 import { withRender } from './with-render';
 import { withUnique } from './with-unique';
 
+const _preactDom = sym('_preactDom');
+
 export const withComponent = (Base = HTMLElement) => class extends withUnique(withRender(withProps(Base))) {
   rendererCallback (shadowRoot, renderCallback) {
-    render(renderCallback(), shadowRoot);
+    const dom = render(renderCallback(), shadowRoot, this[_preactDom]);
+    if (!this[_preactDom]) {
```
Comment (treshugart) [inline src/with-component.js]: I wonder if you even have to have this check? Could you just do something like:

```js
this[_preactDom] = render(renderCallback(), shadowRoot, this[_preactDom]);
```

Comment (matthewp) [inline src/with-component.js]: I always have avoided that out of perf fears. Is setting a property over-and-over again like that basically ignored when you're setting it to the same value over time?  Or is the branching caused by a conditional worse?

Comment (treshugart) [inline src/with-component.js]: Given you can get tens of millions of operations per second setting a property, I don't feel that it would matter too much. Happy to keep as is if you feel it's better. I think the Preact MO is just starting to rub off on me and I was trying to save a few bytes :)

**Comment by treshugart** [comment]
Do whatever you think is best. Merge when you feel comfortable.

File: src/with-component.js (hunk 1 above)
Comment (matthewp) [inline src/with-component.js]: That's fair too, I hadn't thought about size. I have no problem changing it. I am curious which is better thought, probably you're right that the branching is worse. I don't know why my instinct is to add the diff.

**Comment by matthewp** [comment]
I did what they tell you to do when facing a hard comp sci problem; ask the experts on twitter: https://twitter.com/matthewcp/status/852944353911853058

Storing the value sounds fine, so went with that for the size savings. Will merge when tests pass.
