### PR TITLE
fix(vdom): Fix skipping algorithm so that it skips immedate children …

### LINKED ISSUE #731: Skipping doesn't work on immediate children
The following:

```js
vdom.element('div', { skip: true }, () => {
  vdom.text('1');
  vdom.element('span', () => vdom.text('2'));
});
```

Will output:

```js
1
```

But it shouldn't output anything.

### PR DESCRIPTION
**Pull request by treshugart**
…and descendants.

Fixes #731

### CODE REVIEW

File: src/api/vdom.js [hunk 1]
```diff
@@ -166,17 +166,25 @@ function wrapIdomFunc(func, tnameFuncHandler = () => {}) {
...
+        }
       }
+      
+      if (isElementClosing) {
+        let elem = currentElement();
 
-      const elem = func(...args);
+        if (elem[$skipCurrentElement]) {
+          skipCurrentTree = false;
+        } else {
```
Comment (bradleyayers) [inline src/api/vdom.js]: Shouldn't this be `else if (!skipCurrentTree) {`?

File: test/unit/vdom/skip.js [hunk 2]
```diff
@@ -10,6 +10,7 @@ describe('vdom/skip', () => {
       },
       render() {
         vdom.element('div', { skip: true }, () => {
+          vdom.text('text');
```
Comment (bradleyayers) [inline test/unit/vdom/skip.js]: Why is this added?

Comment (treshugart) [inline test/unit/vdom/skip.js]: Yeah, but more importantly immediate children in general. That's what was broken. I should probably be checking `innerHTML` rather that `textContent` below to test both.

File: src/api/vdom.js (hunk 1 above)
Comment (treshugart) [inline src/api/vdom.js]: Good point. I'm not sure why it would be passing then, though. I'll investigate.

File: test/unit/vdom/skip.js (hunk 2 above)
Comment (nadiam84) [inline test/unit/vdom/skip.js]: `render() {
        vdom.element('div', { skip: true }, () => {
          vdom.element('span', () => {
            vdom.text('text');
          });
          vdom.element('span', () => {
            vdom.text('text');
          });
        });
      },`

render function like this will fail the test

File: src/api/vdom.js [hunk 3]
```diff
@@ -166,17 +166,25 @@ function wrapIdomFunc(func, tnameFuncHandler = () => {}) {
...
+          return elem;
+        }
       }
+      
+      if (isElementClosing) {
+        let elem = currentElement();
 
-      const elem = func(...args);
+        if (elem[$skipCurrentElement]) {
+          skipCurrentTree = false;
```
Comment (bradleyayers) [inline src/api/vdom.js]: Shouldn't we call [`skipNode`](https://github.com/google/incremental-dom/blob/master/src/core.js#L452) here too?

Comment (treshugart) [inline src/api/vdom.js]: We're using the latest version. Skate's `skip` functionality is just an abstraction over Incremental DOM's which allows you to be more declarative in how you do it.

File: test/unit/vdom/skip.js (hunk 2 above)
Comment (treshugart) [inline test/unit/vdom/skip.js]: Thanks @nadiam84 will add that to the test cases.

File: src/api/vdom.js (hunk 1 above)
Comment (treshugart) [inline src/api/vdom.js]: K @bradleyayers updated the PR. Logic changed substantially because we now have to keep track of how many levels deep past the skipped element because `currentElement()` doesn't actually return the element we think it does. In IDOM master `currentPointer()` would be used.

File: test/unit/vdom/skip.js (hunk 2 above)
Comment (treshugart) [inline test/unit/vdom/skip.js]: @nadiam84 I've updated the tests. Can you pls have a look when you have a chance? Thanks!

File: test/unit/vdom/skip.js [hunk 4]
```diff
@@ -10,8 +10,14 @@ describe('vdom/skip', () => {
       },
       render() {
         vdom.element('div', { skip: true }, () => {
```
Comment (nadiam84) [inline test/unit/vdom/skip.js]: 'it should not affect siblings' (probably)?
```
render() {
        vdom.element('div', { skip: true }, () => {
          vdom.text('child')
        });
        vdom.element('div', () => {
          vdom.text('sibling')
        });
      },
```
```
expect(elem[symbols.shadowRoot].textContent).to.equal('sibling'),
```
fails

Comment (treshugart) [inline test/unit/vdom/skip.js]: Awesome. Thank you!

File: test/unit/vdom/skip.js [hunk 5]
```diff
@@ -2,26 +2,69 @@ import { define, prop, props, symbols, vdom } from '../../../src/index';
...
+          elementClose('span');
+          elementOpen('div');
+            text('14 ');
+            elementOpen('span');
+              text('15');
+            elementClose('span');
+          elementClose('div');
+        elementClose('div');
       },
     });
```
Comment (nadiam84) [inline test/unit/vdom/skip.js]: That is one horrible looking test :D

```
render() {
        vdom.element('div', () => {
          vdom.element('div', {skip: true}, () => {
            vdom.text('1');
          })
        });
        vdom.element('div', () => {
          vdom.text('2');
        });
      },
```
```
expect(sr(elem).innerHTML).to.equal("<div><div></div></div><div>2</div>")
```
fails

Comment (treshugart) [inline test/unit/vdom/skip.js]: Fixed!

Comment (nadiam84) [inline test/unit/vdom/skip.js]: What about the situation 'a custom element inside a custom element'? Should `skip` affect another custom element's behavior?
What should happen here:
```
const Elem2 = define('x-test2', {
      render() {
        vdom.element('div', () => {
          vdom.text('2');
          vdom.element('slot');
        });
      },
    });
    const Elem = define('x-test', {
      render() {
        vdom.element('x-test2', {skip: true}, () => {
          vdom.element('div', () => {
            vdom.text('1');
          });
        });
      },
    });
```
Right now '2' and 'slot' are rendering despite `{skip: true}` for the x-test2.

Comment (treshugart) [inline test/unit/vdom/skip.js]: That's expected because of the shadow boundary. We expect shadow DOM and
custom elements to abide by the rules of normal DOM so I don't think we
need to make any special considerations here.

**Comment by nadiam84** [comment]
lgtm

File: src/api/vdom.js [hunk 6]
```diff
@@ -78,9 +77,9 @@ attributes.ref = function (elem, name, value) {
 attributes.skip = function (elem, name, value) {
   if (value) {
     skip();
-    elem[$skipCurrentElement] = true;
+    elem.__skip = true;
   } else {
-    delete elem[$skipCurrentElement];
+    delete elem.__skip;
```
Comment (bradleyayers) [inline src/api/vdom.js]: Wouldn't it be better to just remove the `__skip` on the way out of `elementClose`?

Comment (treshugart) [inline src/api/vdom.js]: Skip should remain `true` until it changes.

**Comment by bradleyayers** [comment]
LGTM

**Comment by treshugart** [comment]
lgtm (interesting it didn't pass this check with two maintainers doing it)
