### PR TITLE
fix: play nice with other libraries touching the idom.attributes global

### LINKED ISSUE #745: Multiple skate versions are incompatible when idom.attributes mutation differs
There's a fundamental problem in living up to

> It works with multiple versions of itself on the page.

due to how skate hooks into incremental-dom. incremental-dom exposes an `attributes` object which can be used to hook into the lifecycle of DOM updates, and skate leverages this to do some internal state tracking.

Unfortunately skate currently assumes that it can safely mutate `attributes.___`, but it forgot that it'll actually be stepping on other versions of itself.

This happened in practice with v1.0.0-beta12 and v1.2.3, because back in v1.0.0-beta12 we had the code:

```
// Attributes that are not handled by Incremental DOM.
attributes.key = attributes.skip = attributes.statics = function () {};
```

but in v1.2.3 we *do* need `attributes.skip` so we have:

```
// Skip handler.
incrementalDom.attributes.skip = function (elem, name, value) {
  if (value) {
    elem[$skip] = true;
  } else {
    delete elem[$skip];
  }
};
```

Unfortunately for me v1.0.0-beta12 was being executed *after* v1.2.3 and clobbering the `attributes.skip` hook.

### PR DESCRIPTION
**Pull request by bradleyayers**
fixes #745

### CODE REVIEW

File: src/api/vdom.js [hunk 1]
```diff
@@ -258,7 +267,7 @@ const newElementOpenEnd = wrapIdomFunc(elementOpenEnd);
 
 // Standard open / closed overrides don't need to reproduce internal behaviour
 // because they are the ones referenced from *End and *Start.
-const newElementOpen = wrapIdomFunc(elementOpen, stackOpen);
+const newElementOpen = attributesContext(wrapIdomFunc(elementOpen, stackOpen));
```
Comment (treshugart) [inline src/api/vdom.js]: How can we be sure that this is the only function we need to wrap? Are there any performance implications with this do you think?

File: src/util/prop-context.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
+import assign from './assign';
+
+function enter(object, props) {
+  const saved = {};
+  Object.keys(props).forEach(key => {
```
Comment (treshugart) [inline src/util/prop-context.js]: Could this be a `reduce()`?

**Comment by treshugart** [comment]
lgtm pending comments

File: src/api/vdom.js (hunk 1 above)
Comment (bradleyayers) [inline src/api/vdom.js]: Yes this is the only function. There might be performance implications, but I think at this point they're of less concern than the multi-version incompatibility, and something we could improve later.

File: src/util/prop-context.js (hunk 2 above)
Comment (bradleyayers) [inline src/util/prop-context.js]: Semantically `reduce` is used to build and return a *new* object based on collection, but in this case that isn't our goal. Instead we want to mutate and existing one (`object`).

We could certainly *exploit* the looping behaviour of `reduce` for this, but unless it brings a perf improvement I don't think it would be mislead the reader.

File: src/api/vdom.js (hunk 1 above)
Comment (bradleyayers) [inline src/api/vdom.js]: Perhaps a useful upstream change to incremental-dom would be to allow the entire attributes object to be changed, rather than just attributes on it. This would allow context switches to be faster (single assignment operation) rather than being proportional to the number of attribute overrides.

**Comment by bradleyayers** [comment]
lgtm

File: src/api/vdom.js (hunk 1 above)
Comment (treshugart) [inline src/api/vdom.js]: The idea would be to pass `attributes` in to every patch and patch would look to that as the source of truth instead of the global.

File: src/util/prop-context.js (hunk 2 above)
Comment (treshugart) [inline src/util/prop-context.js]: Yeah, I can see that now.
